# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18TL8Tbn8QvMDWyNGYhuKAWPPTblBANkn
"""

print("Hello World")